from __future__ import annotations

import pytest

from schemaguard.transformations.inventory import DATASET_IDS, SEEDS, VIEW_IDS
from schemaguard.transformations.registry import load_transformation_config


@pytest.mark.integration
@pytest.mark.slow
def test_transformation_registry_matrix_is_frozen() -> None:
    config = load_transformation_config("configs/runtime/transformation_engine.yaml")
    assert len(DATASET_IDS) * len(SEEDS) * len(VIEW_IDS) == 770
    assert [item["id"] for item in config.views] == VIEW_IDS


@pytest.mark.integration
@pytest.mark.evidence
def test_materialized_inventory_is_strict_when_present() -> None:
    import json
    from pathlib import Path

    path = Path("artifacts/handoff/transformation_inventory.json")
    if not path.is_file():
        pytest.skip("full transformation inventory is generated by the validation command")
    from schemaguard.transformations.contracts import TransformationInventory

    inventory = TransformationInventory.model_validate(json.loads(path.read_text(encoding="utf-8")))
    assert inventory.expected_record_count == 770
