from __future__ import annotations

import json
from pathlib import Path

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from schemaguard.transformations.certificates import validate_roundtrip
from schemaguard.transformations.numeric_affine import NumericAffineTransformation

from .transformation_helpers import sample_frame, sample_schema, target_hash


@settings(max_examples=1000, deadline=None, derandomize=True)
@given(st.lists(st.integers(min_value=-1000, max_value=1000), min_size=5, max_size=20))
def test_affine_roundtrip_property(values: list[int]) -> None:
    frame = sample_frame().iloc[[index % 12 for index in range(len(values))]].reset_index(drop=True)
    frame["__sg_row_id"] = [f"property-row-{index}" for index in range(len(values))]
    frame["amount"] = [float(value) for value in values]
    transformation = NumericAffineTransformation({"max_numeric_columns": 1}).fit(
        frame, 1464, 1729, sample_schema(frame)
    )
    output = transformation.transform(frame, "train")
    certificate = transformation.certificate_for(
        frame,
        output,
        "train",
        source_target_hash=target_hash(frame),
        output_target_hash=target_hash(frame),
    )
    restored = transformation.reconstruct(output, certificate)
    assert validate_roundtrip(frame, output, restored, certificate)["status"] == "PASS"


@pytest.mark.evidence
def test_all_views_have_real_property_evidence() -> None:
    path = Path("artifacts/handoff/transformation_property_evidence.json")
    if not path.is_file():
        pytest.skip("property evidence is generated by the property runner")
    evidence = json.loads(path.read_text(encoding="utf-8"))
    assert {item["view_id"] for item in evidence} == {f"V{index:02d}" for index in range(11)}
    assert all(item["executed_example_count"] >= 1000 for item in evidence)
    assert all(item["failed_example_count"] == 0 for item in evidence)
